// src/lib/nicheSiteTemplates.ts — v180
//
// The "free website" template engine. Each niche is a config object that
// renders a complete premium one-page site via NicheSiteTemplate.tsx.
// Hand a prospect /template/<niche>?company=Their%20Co and they see THEIR
// business with a working-looking voice agent + chatbot demo, in our brand.
// Swap the name + a couple fields = instant pitch asset. Zero code per deal.
//
// Brand is locked to the TYA system (cream/navy/Playfair). Each niche carries
// its own accent so sites feel distinct without leaving the brand.

export type NicheChatExchange = { from: "customer" | "agent"; text: string };

export type NicheSite = {
  id: string;
  niche: string;            // display label, e.g. "Cleaning Service"
  emoji: string;            // light visual marker for the gallery
  accent: string;           // hex accent (stays in-brand family)
  defaultCompany: string;   // placeholder business name
  city: string;             // placeholder city
  // hero
  heroLead: string;         // bold sans first clause
  heroItalic: string;       // Playfair italic accent clause
  subhead: string;          // one-line value prop
  // proof chips under hero
  chips: string[];
  // services grid (4)
  services: { title: string; body: string }[];
  // the missed-call pain stat
  painStat: string;
  painLabel: string;
  // voice agent demo
  voiceGreeting: string;    // what the agent says on pickup
  voiceTryLines: string[];  // sample caller prompts
  // chatbot demo
  chat: NicheChatExchange[];
  // pricing line
  priceLine: string;
  // v193: pull a niche out of circulation without deleting the data — gallery
  // hides it, the public /template/[id] route 404s with a "template-not-found"
  // message. Useful when a vertical has temporary compliance / legal issues.
  disabled?: boolean;

  // v208: OPTIONAL 2030-tier extensions. All have sensible defaults derived in
  // NicheSiteTemplate.tsx, so existing data still renders the full premium site.
  // Authors can override per-niche later for higher-conversion specifics.
  reviews?: { name: string; city?: string; stars: number; text: string }[];
  faq?: { q: string; a: string }[];
  pricingTiers?: { name: string; price: string; period: string; features: string[]; featured?: boolean; cta?: string }[];
  quoteCalc?: {
    label: string;
    sliders: { key: string; label: string; min: number; max: number; step: number; default: number; unit?: string; unitPrice: number }[];
    basePrice: number;
    unit?: string; // e.g. "$" — defaults to "$"
    footnote?: string;
  };
  serviceArea?: string[];           // neighborhoods/cities served
  liveActivity?: string[];          // short ticker lines, {co} token replaced
  trustBadges?: string[];           // small text-based proof badges
  quickReplies?: string[];          // chat quick-reply chips
  // optional micro-stats row (defaults computed if missing)
  statBlocks?: { number: string; label: string }[];

  // v221: competitor-parity layer — what every legit local business has on
  // their actual website. Each niche supplies its own; defaults computed if
  // missing. This is the layer that makes the page indistinguishable from
  // a 10-year-old established operator instead of an AI template.
  serviceCatalog?: { name: string; price: string; period?: string; note?: string }[];
  brandsServiced?: string[];      // equipment / insurance / partner brands
  certifications?: string[];      // industry-specific trust badges
  licenseFormat?: string;         // e.g. "FL CAC #" — drives the footer license line
};

export const NICHE_SITES: NicheSite[] = [
  {
    id: "cleaning",
    niche: "Cleaning Service",
    emoji: "🧽",
    accent: "#0E7C7B",
    defaultCompany: "SparkleHouse Cleaning",
    city: "Tampa",
    heroLead: "Every booking request answered",
    heroItalic: "before your competitor picks up.",
    subhead: "Your AI receptionist books recurring cleans, quotes square footage, and fills cancellations — 24/7, on your existing number.",
    chips: ["Recurring bookings", "Instant quotes", "Cancellation fills", "Spanish + English"],
    services: [
      { title: "Residential cleaning", body: "Weekly, biweekly, monthly recurring plans booked and confirmed automatically." },
      { title: "Move-in / move-out", body: "Square-footage quoted on the call, deposit link texted before you hang up." },
      { title: "Commercial contracts", body: "After-hours office and retail cleans scheduled around your crews." },
      { title: "Deep & post-construction", body: "Add-on scoping, photos requested, same-day estimate sent." },
    ],
    painStat: "1 in 3",
    painLabel: "cleaning leads call a competitor when you don't answer",
    voiceGreeting: "Thanks for calling {co} — this is your assistant. Are you looking for a recurring clean, a one-time deep clean, or a move-out?",
    voiceTryLines: ["“I need a 3-bedroom cleaned before Friday.”", "“How much for biweekly?”", "“Do you do move-out cleans?”"],
    chat: [
      { from: "customer", text: "Do you have anything this weekend?" },
      { from: "agent", text: "We do — Saturday 9am or Sunday 1pm are open for a standard clean. How many bedrooms and bathrooms?" },
      { from: "customer", text: "3 bed 2 bath" },
      { from: "agent", text: "That's $180 for a standard clean. Want me to lock Saturday 9am and text you a confirmation?" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "laundromat",
    niche: "Laundromat / Wash & Fold",
    emoji: "🧺",
    accent: "#2563A8",
    defaultCompany: "FreshFold Laundry",
    city: "Tampa",
    heroLead: "Pickup, delivery, and wash-&-fold orders",
    heroItalic: "taken while you run the floor.",
    subhead: "An AI line that schedules pickups, quotes by the pound, and answers hours-and-machines questions so your staff never stops folding.",
    chips: ["Pickup scheduling", "Per-pound quotes", "Route windows", "Loyalty signups"],
    services: [
      { title: "Wash & fold", body: "Per-pound orders booked with pickup and drop-off windows confirmed by text." },
      { title: "Pickup & delivery", body: "Address captured, route window assigned, customer notified automatically." },
      { title: "Commercial laundry", body: "Restaurants, gyms, and salons set up on recurring contracts." },
      { title: "Self-serve support", body: "Hours, machine availability, and card-reload questions answered 24/7." },
    ],
    painStat: "62%",
    painLabel: "of pickup requests come outside staffed hours",
    voiceGreeting: "Thanks for calling {co} — want to schedule a wash-and-fold pickup, or check on an order?",
    voiceTryLines: ["“Can you pick up tomorrow morning?”", "“How much per pound?”", "“Are you open right now?”"],
    chat: [
      { from: "customer", text: "Do you pick up in Seminole Heights?" },
      { from: "agent", text: "We do! Pickups there run 8–10am. About how many pounds, roughly?" },
      { from: "customer", text: "Maybe 20 lbs" },
      { from: "agent", text: "That's around $35 wash-and-fold. Want tomorrow's 8–10 window? I'll text you the confirmation." },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "hvac",
    niche: "HVAC",
    emoji: "❄️",
    accent: "#185FA5",
    defaultCompany: "Bay Area Air & Heat",
    city: "Tampa",
    heroLead: "Every after-hours emergency call",
    heroItalic: "becomes a booked job.",
    subhead: "Your agent triages emergency vs. routine, quotes the dispatch fee, and books the tech truck — even at 2am during a heat wave.",
    chips: ["Emergency triage", "Dispatch quoting", "Service booking", "Maintenance plans"],
    services: [
      { title: "Emergency dispatch", body: "After-hours calls triaged, fee quoted, and the on-call tech booked instantly." },
      { title: "Service scheduling", body: "Tune-ups and repairs slotted into your calendar with the right window." },
      { title: "Maintenance plans", body: "Recurring memberships sold and renewed on the call." },
      { title: "Install quotes", body: "System replacement leads captured and routed to your closer same day." },
    ],
    painStat: "$180K",
    painLabel: "average annual revenue lost to missed HVAC calls",
    voiceGreeting: "Thanks for calling {co} — is this an emergency, or are you scheduling routine service?",
    voiceTryLines: ["“My AC died and it's 95 degrees.”", "“What's your dispatch fee?”", "“Can someone come tomorrow?”"],
    chat: [
      { from: "customer", text: "AC stopped working, house is getting hot" },
      { from: "agent", text: "Sorry to hear that — is anyone home medically vulnerable, or pets in the heat?" },
      { from: "customer", text: "Just us, but it's bad" },
      { from: "agent", text: "I can get a tech out today between 2–4pm. Dispatch is $89, applied to the repair. Want me to book it?" },
    ],
    priceLine: "Live on your phone line in 14 days · from $1,997/mo",
  },
  {
    id: "dental",
    niche: "Dental Practice",
    emoji: "🦷",
    accent: "#0C8A6E",
    defaultCompany: "Bayshore Family Dental",
    city: "Tampa",
    heroLead: "New-patient calls booked",
    heroItalic: "without pulling your front desk away.",
    subhead: "An AI receptionist that books cleanings, screens insurance, handles reschedules, and fills last-minute cancellations.",
    chips: ["New-patient intake", "Insurance screening", "Reschedules", "Recall reminders"],
    services: [
      { title: "New-patient booking", body: "Insurance captured, first cleaning scheduled, paperwork link texted." },
      { title: "Cancellation fills", body: "Open slots offered to your waitlist automatically the moment they appear." },
      { title: "Recall & hygiene", body: "Six-month recall calls handled so chairs stay full." },
      { title: "After-hours triage", body: "Emergencies routed, everything else booked for the next open slot." },
    ],
    painStat: "35%",
    painLabel: "of new-patient calls go to voicemail and never call back",
    voiceGreeting: "Thank you for calling {co} — are you a new patient, or scheduling a follow-up?",
    voiceTryLines: ["“I need a cleaning, I'm a new patient.”", "“Do you take Delta Dental?”", "“Can I move my appointment?”"],
    chat: [
      { from: "customer", text: "Are you taking new patients?" },
      { from: "agent", text: "We are! Do you have dental insurance you'd like me to note, or are you paying out of pocket?" },
      { from: "customer", text: "I have Cigna" },
      { from: "agent", text: "Perfect, we're in-network. I have next Tuesday 10am or Thursday 2pm for your first cleaning — which works?" },
    ],
    priceLine: "Live on your phone line in 14 days · HIPAA BAA included",
  },
  {
    id: "salon",
    niche: "Salon & Spa",
    emoji: "💇",
    accent: "#A24598",
    defaultCompany: "Lume Salon & Spa",
    city: "Tampa",
    heroLead: "Every appointment request booked",
    heroItalic: "while your stylists stay with clients.",
    subhead: "Your agent books color, cuts, and treatments, quotes by service, and fills late cancellations from your waitlist.",
    chips: ["Service booking", "Stylist matching", "Waitlist fills", "Deposit links"],
    services: [
      { title: "Appointment booking", body: "Color, cut, and treatment slots booked to the right stylist's calendar." },
      { title: "Deposit collection", body: "No-show protection — deposit link texted before the slot is held." },
      { title: "Waitlist fills", body: "Cancellations instantly offered to waiting clients." },
      { title: "Package upsells", body: "Add-ons and membership packages offered naturally on the call." },
    ],
    painStat: "1 in 4",
    painLabel: "booking calls come in while every chair is busy",
    voiceGreeting: "Thanks for calling {co} — what service can I book for you today?",
    voiceTryLines: ["“I want a balayage next week.”", "“How much for a cut and color?”", "“Do you have anything Saturday?”"],
    chat: [
      { from: "customer", text: "Do you have color availability this week?" },
      { from: "agent", text: "Yes! Are you thinking full color, highlights, or a balayage?" },
      { from: "customer", text: "Balayage" },
      { from: "agent", text: "With Maya I have Thursday 1pm or Friday 11am. It's $185 and I'll text a $40 deposit link to hold it — which day?" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "auto",
    niche: "Auto Repair",
    emoji: "🔧",
    accent: "#B45309",
    defaultCompany: "Gulf Coast Auto",
    city: "Tampa",
    heroLead: "Service-bay appointments booked",
    heroItalic: "without a tech wiping their hands to grab the phone.",
    subhead: "An AI line that books diagnostics, quotes common jobs, and schedules around your bay capacity.",
    chips: ["Bay scheduling", "Job quoting", "Status updates", "Tow coordination"],
    services: [
      { title: "Appointment booking", body: "Diagnostics and repairs slotted around real bay availability." },
      { title: "Common-job quotes", body: "Brakes, oil, tires quoted on the call with parts lead-time noted." },
      { title: "Status callbacks", body: "Customers get proactive updates instead of calling to check in." },
      { title: "Tow & after-hours", body: "Breakdown calls captured overnight and booked for the morning." },
    ],
    painStat: "48%",
    painLabel: "of repair calls hit voicemail during busy bay hours",
    voiceGreeting: "Thanks for calling {co} — are you booking service, or checking on a vehicle that's with us?",
    voiceTryLines: ["“My check-engine light is on.”", "“How much for front brakes?”", "“Can I drop off tomorrow?”"],
    chat: [
      { from: "customer", text: "Need a brake job, how much?" },
      { from: "agent", text: "Front pads and rotors on most cars run $280–$340. What's the year, make, and model?" },
      { from: "customer", text: "2018 Honda Accord" },
      { from: "agent", text: "That's $295 out the door. I can get you a bay tomorrow at 8am or 1pm — which works?" },
    ],
    priceLine: "Live on your phone line in 10 days · from $1,997/mo",
  },
  {
    id: "landscaping",
    niche: "Landscaping & Lawn",
    emoji: "🌳",
    accent: "#3F8A2E",
    defaultCompany: "EverGreen Outdoor",
    city: "Tampa",
    heroLead: "Estimate requests captured",
    heroItalic: "before the crew's even off the truck.",
    subhead: "Your agent books estimates, sells recurring maintenance, and routes by neighborhood so your trucks stay efficient.",
    chips: ["Estimate booking", "Recurring plans", "Route batching", "Seasonal upsells"],
    services: [
      { title: "Estimate scheduling", body: "Property address captured, walkthrough booked, photos requested up front." },
      { title: "Recurring maintenance", body: "Weekly and biweekly mowing plans sold and confirmed on the call." },
      { title: "Project quoting", body: "Sod, mulch, and hardscape leads scoped and routed to your estimator." },
      { title: "Seasonal pushes", body: "Cleanups and irrigation checks offered when the season turns." },
    ],
    painStat: "$140K",
    painLabel: "average revenue lost yearly to unanswered estimate calls",
    voiceGreeting: "Thanks for calling {co} — are you looking for recurring lawn care, or a one-time project?",
    voiceTryLines: ["“I need weekly mowing.”", "“Can you quote sod install?”", "“How soon can someone look at my yard?”"],
    chat: [
      { from: "customer", text: "Do you do weekly mowing in Carrollwood?" },
      { from: "agent", text: "We do! For an average quarter-acre lot weekly service is about $140/mo. What's the address so I can confirm the route day?" },
      { from: "customer", text: "It's a corner lot, a bit bigger" },
      { from: "agent", text: "Got it — I'll book a quick walkthrough Wednesday 9am and lock your weekly slot. Sound good?" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "plumbing",
    niche: "Plumbing",
    emoji: "🚰",
    accent: "#1E6FB8",
    defaultCompany: "TrueFlow Plumbing",
    city: "Tampa",
    heroLead: "Every burst-pipe call answered",
    heroItalic: "and dispatched in under a minute.",
    subhead: "An AI line that triages emergencies, quotes the trip charge, and books the truck — day or night.",
    chips: ["Emergency dispatch", "Trip-fee quoting", "Job scheduling", "Photo intake"],
    services: [
      { title: "Emergency response", body: "Leaks and backups triaged, fee quoted, nearest tech dispatched." },
      { title: "Scheduled repairs", body: "Water heaters, fixtures, and re-pipes booked to your calendar." },
      { title: "Quote-on-call", body: "Common jobs priced instantly; photos requested to firm it up." },
      { title: "After-hours capture", body: "Overnight calls booked for first thing instead of lost to voicemail." },
    ],
    painStat: "67%",
    painLabel: "of plumbing emergencies happen outside business hours",
    voiceGreeting: "Thanks for calling {co} — is this an active leak or emergency, or are you scheduling a repair?",
    voiceTryLines: ["“My water heater is leaking everywhere.”", "“What's your trip charge?”", "“Can you come tonight?”"],
    chat: [
      { from: "customer", text: "Water heater is leaking, kind of bad" },
      { from: "agent", text: "Let's get someone out. Is the water shut off at the valve, or still running?" },
      { from: "customer", text: "Still running" },
      { from: "agent", text: "Turn the valve clockwise to stop it — I'm dispatching a tech now, ETA 45 min, $99 trip applied to the repair." },
    ],
    priceLine: "Live on your phone line in 10 days · from $1,997/mo",
  },
  {
    id: "restaurant",
    niche: "Restaurant",
    emoji: "🍽️",
    accent: "#C2410C",
    defaultCompany: "Casa Verde Kitchen",
    city: "Tampa",
    heroLead: "Reservations, takeout, and catering",
    heroItalic: "handled without tying up the line.",
    subhead: "Your agent takes reservations, quotes catering, and answers hours-and-menu questions so your hosts stay with guests.",
    chips: ["Reservations", "Takeout orders", "Catering quotes", "Waitlist"],
    services: [
      { title: "Reservations", body: "Party size and time booked straight into your floor plan." },
      { title: "Takeout & pickup", body: "Orders captured and timed; payment link texted ahead." },
      { title: "Catering leads", body: "Event details scoped and routed to your catering manager." },
      { title: "FAQ deflection", body: "Hours, parking, allergens, and menu questions answered 24/7." },
    ],
    painStat: "30%",
    painLabel: "of dinner-rush calls go unanswered",
    voiceGreeting: "Thanks for calling {co} — would you like a reservation, takeout, or catering?",
    voiceTryLines: ["“Table for 4 at 7?”", "“Do you cater for 40 people?”", "“What are your hours?”"],
    chat: [
      { from: "customer", text: "Can I get a table for 4 tonight at 7:30?" },
      { from: "agent", text: "Let me check — yes, 7:30 for 4 is open. Any seating preference, patio or inside?" },
      { from: "customer", text: "Patio please" },
      { from: "agent", text: "Done — patio table for 4 at 7:30 under your name. I'll text a confirmation. See you tonight!" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "fitness",
    niche: "Gym & Fitness Studio",
    emoji: "🏋️",
    accent: "#7C3AED",
    defaultCompany: "Iron Bay Fitness",
    city: "Tampa",
    heroLead: "Every membership inquiry booked",
    heroItalic: "into a tour before they cool off.",
    subhead: "An AI line that books tours, sells trials, answers class schedules, and handles freeze-and-cancel requests.",
    chips: ["Tour booking", "Trial signups", "Class schedules", "Membership admin"],
    services: [
      { title: "Tour & trial booking", body: "Prospects booked into a tour or free trial the moment they call." },
      { title: "Class scheduling", body: "Spots reserved and waitlists managed across your timetable." },
      { title: "Membership admin", body: "Freezes, upgrades, and cancellations handled by policy, no front-desk time." },
      { title: "Win-back", body: "Lapsed members re-engaged with the right offer automatically." },
    ],
    painStat: "1 in 3",
    painLabel: "membership inquiries never get a callback",
    voiceGreeting: "Thanks for calling {co} — are you interested in a tour, a free trial, or class info?",
    voiceTryLines: ["“Can I come check out the gym?”", "“Do you have a free trial?”", "“What time is the 6am class?”"],
    chat: [
      { from: "customer", text: "Do you offer a trial?" },
      { from: "agent", text: "We do — a free 3-day pass. Want me to set it up? I'll just need your name and the best number to text the pass to." },
      { from: "customer", text: "Sure, sounds good" },
      { from: "agent", text: "You're all set — pass texted, valid starting tomorrow. Want me to book a quick tour for your first visit?" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "real-estate",
    niche: "Real Estate",
    emoji: "🏡",
    accent: "#0F766E",
    defaultCompany: "Bayfront Realty Group",
    city: "Tampa",
    heroLead: "Every buyer + seller lead worked",
    heroItalic: "the second it comes in.",
    subhead: "Your AI line captures inquiries, qualifies budget and timeline, books showings, and routes hot leads to the right agent instantly.",
    chips: ["Lead qualification", "Showing scheduling", "Listing inquiries", "Agent routing"],
    services: [
      { title: "Buyer lead intake", body: "Budget, timeline, and pre-approval captured before the lead goes cold." },
      { title: "Showing scheduling", body: "Tours booked into the right agent's calendar with the property details attached." },
      { title: "Listing inquiries", body: "Callers on your signs and portals answered 24/7 with the listing facts." },
      { title: "Seller intake", body: "Valuation requests captured and routed to your listing specialist same day." },
    ],
    painStat: "48%",
    painLabel: "of real-estate leads go to the first agent who responds",
    voiceGreeting: "Thanks for calling {co} — are you looking to buy, sell, or see a specific listing?",
    voiceTryLines: ["“I saw your sign on Bayshore.”", "“What's my home worth?”", "“Can I tour it this weekend?”"],
    chat: [
      { from: "customer", text: "Is the listing on Maple still available?" },
      { from: "agent", text: "It is! Are you pre-approved, and what's your ideal move-in timeline?" },
      { from: "customer", text: "Pre-approved, looking in 60 days" },
      { from: "agent", text: "Great fit. I can book a showing Saturday 11am or Sunday 2pm with our agent Dana — which works?" },
    ],
    priceLine: "Live on your phone line in 10 days · from $1,997/mo",
  },
  {
    id: "law-firm",
    niche: "Law Firm",
    emoji: "⚖️",
    accent: "#1E3A5F",
    defaultCompany: "Harbor Legal",
    city: "Tampa",
    heroLead: "Every intake call captured",
    heroItalic: "and conflict-checked before it walks.",
    subhead: "Your AI intake line screens case type, runs a basic conflict check, books the consult, and never lets a qualified lead hit voicemail.",
    chips: ["Case-type screening", "Conflict checks", "Consult booking", "After-hours intake"],
    services: [
      { title: "New-client intake", body: "Case type, jurisdiction, and urgency captured to a structured intake form." },
      { title: "Consult scheduling", body: "Qualified callers booked directly into the right attorney's calendar." },
      { title: "Conflict pre-check", body: "Opposing-party name captured up front so your team can clear conflicts fast." },
      { title: "After-hours coverage", body: "Injury and emergency matters captured overnight, routed by morning." },
    ],
    painStat: "42%",
    painLabel: "of legal intake calls are never returned in time to sign the client",
    voiceGreeting: "Thank you for calling {co} — can you tell me briefly what kind of matter you're calling about?",
    voiceTryLines: ["“I was in a car accident.”", "“I need help with a contract.”", "“Do you do free consults?”"],
    chat: [
      { from: "customer", text: "I was rear-ended last week, do I have a case?" },
      { from: "agent", text: "I'm sorry that happened. Were you injured, and did you receive any medical treatment?" },
      { from: "customer", text: "Yeah, went to the ER" },
      { from: "agent", text: "That's worth a consult. I can book you with one of our injury attorneys today at 3pm or tomorrow 10am — which works?" },
    ],
    priceLine: "Live on your phone line in 14 days · intake confidentiality built in",
  },
  {
    id: "roofing",
    niche: "Roofing",
    emoji: "🏠",
    accent: "#9A3412",
    defaultCompany: "Summit Roofing Co.",
    city: "Tampa",
    heroLead: "Storm-season estimate calls booked",
    heroItalic: "before the next contractor calls back.",
    subhead: "Your AI line captures damage details, books free inspections, and handles the surge when a storm doubles your call volume overnight.",
    chips: ["Inspection booking", "Insurance-claim intake", "Storm surge capacity", "Photo requests"],
    services: [
      { title: "Free-inspection booking", body: "Address and roof age captured, inspection scheduled with the right crew." },
      { title: "Insurance claims", body: "Storm-damage and claim details captured to speed your adjuster process." },
      { title: "Surge handling", body: "When a storm spikes calls 5x, every one is still answered and booked." },
      { title: "Repair vs. replace", body: "Leads triaged so your estimators spend time on the real jobs." },
    ],
    painStat: "$210K",
    painLabel: "average storm-season revenue lost to roofers who can't answer the surge",
    voiceGreeting: "Thanks for calling {co} — are you dealing with a leak, storm damage, or planning a replacement?",
    voiceTryLines: ["“I've got a leak after the storm.”", "“Do you do free inspections?”", "“Will you work with my insurance?”"],
    chat: [
      { from: "customer", text: "Roof started leaking after the hurricane" },
      { from: "agent", text: "Let's get it looked at fast. Is it actively leaking inside right now, and roughly how old is the roof?" },
      { from: "customer", text: "Dripping in the bedroom, roof's about 12 years" },
      { from: "agent", text: "I'll get an inspector out tomorrow morning, free, and we work directly with insurance. Booking 9am — that work?" },
    ],
    priceLine: "Live on your phone line in 10 days · built for storm surge",
  },
  {
    id: "med-spa",
    niche: "Med Spa",
    emoji: "💆",
    accent: "#BE185D",
    defaultCompany: "Glow Aesthetics",
    city: "Tampa",
    heroLead: "Every treatment inquiry booked",
    heroItalic: "while your providers stay in the room.",
    subhead: "Your AI line books Botox, filler, laser, and facials, quotes by treatment, collects deposits, and fills cancellations from your waitlist.",
    chips: ["Treatment booking", "Deposit collection", "Membership upsell", "Waitlist fills"],
    services: [
      { title: "Treatment scheduling", body: "Injectables, laser, and facials booked to the right provider's calendar." },
      { title: "Consult booking", body: "New-client consults captured with goals noted before they arrive." },
      { title: "Deposit + no-show protection", body: "Card-on-file deposit link texted before the slot is held." },
      { title: "Membership growth", body: "Packages and memberships offered naturally on the call." },
    ],
    painStat: "1 in 3",
    painLabel: "med-spa booking calls come in while every provider is with a client",
    voiceGreeting: "Thanks for calling {co} — are you booking a treatment, or would you like a consultation?",
    voiceTryLines: ["“How much is Botox?”", "“Do you do lip filler?”", "“I want a consult for laser.”"],
    chat: [
      { from: "customer", text: "How much for Botox?" },
      { from: "agent", text: "We're $12/unit, most foreheads run 20–30 units. Want me to book you with one of our injectors for an assessment?" },
      { from: "customer", text: "Sure, this week if possible" },
      { from: "agent", text: "Thursday 1pm or Friday 4pm with Dr. Lee — I'll text a $50 deposit link to hold it. Which works?" },
    ],
    priceLine: "Live on your phone line in 10 days · from $1,997/mo",
  },
  {
    id: "chiropractor",
    niche: "Chiropractic",
    emoji: "🦴",
    accent: "#047857",
    defaultCompany: "Align Spine & Wellness",
    city: "Tampa",
    heroLead: "Every new-patient call booked",
    heroItalic: "without pulling your front desk off a patient.",
    subhead: "Your AI line screens insurance, books adjustments and new-patient exams, and fills last-minute openings automatically.",
    chips: ["New-patient exams", "Insurance screening", "Adjustment booking", "Recall reminders"],
    services: [
      { title: "New-patient booking", body: "Insurance and chief complaint captured, first exam scheduled." },
      { title: "Adjustment scheduling", body: "Recurring visits booked around your treatment plans." },
      { title: "Insurance screening", body: "Coverage checked on the call so patients aren't surprised." },
      { title: "Cancellation fills", body: "Open slots offered to your waitlist the moment they appear." },
    ],
    painStat: "38%",
    painLabel: "of new-patient chiro calls hit voicemail and book elsewhere",
    voiceGreeting: "Thanks for calling {co} — are you a new patient, or scheduling a follow-up adjustment?",
    voiceTryLines: ["“My back's been killing me.”", "“Do you take my insurance?”", "“Can I get in today?”"],
    chat: [
      { from: "customer", text: "Lower back pain for a week, are you new-patient friendly?" },
      { from: "agent", text: "Absolutely. Do you have insurance you'd like me to verify, and is the pain limiting your movement?" },
      { from: "customer", text: "I have BCBS, and yeah it's rough" },
      { from: "agent", text: "We're in-network. I can get you a same-day exam at 4:15 or tomorrow 9am — which works?" },
    ],
    priceLine: "Live on your phone line in 14 days · from $1,997/mo",
  },
  {
    id: "pest-control",
    niche: "Pest Control",
    emoji: "🐜",
    accent: "#65A30D",
    defaultCompany: "ShieldGuard Pest",
    city: "Tampa",
    heroLead: "Every infestation call booked",
    heroItalic: "before they call the next guy in panic.",
    subhead: "Your AI line triages the pest, quotes the treatment, books the tech, and sells recurring protection plans 24/7.",
    chips: ["Treatment booking", "Recurring plans", "Emergency triage", "Quote-on-call"],
    services: [
      { title: "Service booking", body: "Pest type and severity captured, the right tech scheduled." },
      { title: "Recurring protection", body: "Quarterly and monthly plans sold and renewed on the call." },
      { title: "Emergency response", body: "Stinging-insect and rodent emergencies triaged and dispatched fast." },
      { title: "Quote-on-call", body: "Common treatments priced instantly with the visit booked." },
    ],
    painStat: "1 in 2",
    painLabel: "pest calls go to whoever answers — panic doesn't wait",
    voiceGreeting: "Thanks for calling {co} — what are you seeing, and is it inside or outside the home?",
    voiceTryLines: ["“I have a wasp nest by the door.”", "“How much for monthly service?”", "“I saw a rat in the kitchen.”"],
    chat: [
      { from: "customer", text: "There's a big wasp nest by my front door" },
      { from: "agent", text: "Let's handle that quickly — is anyone in the home allergic to stings?" },
      { from: "customer", text: "My son is" },
      { from: "agent", text: "I'll prioritize you. A tech can be out today 2–4pm, $129 for nest removal. Want me to book it?" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "electrician",
    niche: "Electrician",
    emoji: "⚡",
    accent: "#CA8A04",
    defaultCompany: "Volt Pro Electric",
    city: "Tampa",
    heroLead: "Every service call captured",
    heroItalic: "without a tech climbing down to answer.",
    subhead: "Your AI line triages electrical emergencies, quotes common jobs, and books the truck around your crew's schedule.",
    chips: ["Emergency triage", "Job quoting", "Panel + EV installs", "After-hours capture"],
    services: [
      { title: "Service booking", body: "Issue captured, the right electrician scheduled with the parts noted." },
      { title: "Emergency response", body: "No-power and burning-smell calls triaged and dispatched immediately." },
      { title: "Install quoting", body: "Panel upgrades, EV chargers, and rewires scoped and routed to your estimator." },
      { title: "After-hours capture", body: "Overnight calls booked for first thing instead of lost." },
    ],
    painStat: "55%",
    painLabel: "of electrical service calls hit voicemail during the workday",
    voiceGreeting: "Thanks for calling {co} — is this an emergency with no power, or are you scheduling work?",
    voiceTryLines: ["“Half my house lost power.”", "“How much for an EV charger?”", "“Can someone come today?”"],
    chat: [
      { from: "customer", text: "Half the outlets in my house just died" },
      { from: "agent", text: "Could be a tripped breaker or a bigger issue — is there any burning smell or breaker that won't reset?" },
      { from: "customer", text: "One breaker won't reset" },
      { from: "agent", text: "Let's get a tech out. I have today 1–3pm, $95 diagnostic applied to the repair. Booking it?" },
    ],
    priceLine: "Live on your phone line in 10 days · from $1,997/mo",
  },
  {
    id: "moving",
    niche: "Moving Company",
    emoji: "📦",
    accent: "#0369A1",
    defaultCompany: "Sunshine Movers",
    city: "Tampa",
    heroLead: "Every moving quote captured",
    heroItalic: "before they price three other crews.",
    subhead: "Your AI line captures move details, quotes by size and distance, books the crew, and locks the date with a deposit.",
    chips: ["Move quoting", "Date booking", "Deposit collection", "Long-distance intake"],
    services: [
      { title: "Quote-on-call", body: "Bedroom count, distance, and date captured for an instant ballpark." },
      { title: "Booking + deposit", body: "Move date locked with a deposit link texted before they shop around." },
      { title: "Long-distance intake", body: "Interstate moves scoped and routed to your logistics coordinator." },
      { title: "Packing add-ons", body: "Packing, storage, and supplies upsold naturally on the call." },
    ],
    painStat: "60%",
    painLabel: "of movers booked are simply the first to call back with a quote",
    voiceGreeting: "Thanks for calling {co} — are you moving locally or long-distance, and what's the size of the move?",
    voiceTryLines: ["“2-bedroom apartment, local.”", "“How much to move to Orlando?”", "“Can you do next Saturday?”"],
    chat: [
      { from: "customer", text: "Need to move a 2-bedroom across town next weekend" },
      { from: "agent", text: "Easy — local 2-bedroom moves run about $650–$850 depending on stairs and access. Ground floor or stairs?" },
      { from: "customer", text: "Second floor, no elevator" },
      { from: "agent", text: "Got it, ~$795. I can hold Saturday with a $100 deposit and text you the link. Lock it in?" },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "veterinary",
    niche: "Veterinary Clinic",
    emoji: "🐾",
    accent: "#0D9488",
    defaultCompany: "Bayside Animal Hospital",
    city: "Tampa",
    heroLead: "Every pet-parent call answered",
    heroItalic: "even when the front desk is in an exam.",
    subhead: "Your AI line books appointments, triages urgent cases, handles prescription refills, and answers hours-and-services questions 24/7.",
    chips: ["Appointment booking", "Urgent triage", "Rx refills", "New-client intake"],
    services: [
      { title: "Appointment booking", body: "Wellness, vaccine, and sick visits scheduled to the right vet." },
      { title: "Urgent triage", body: "Emergencies flagged and routed; routine visits booked next-available." },
      { title: "Prescription refills", body: "Refill requests captured and queued for the vet to approve." },
      { title: "New-client intake", body: "New pets registered with species, breed, and history noted." },
    ],
    painStat: "34%",
    painLabel: "of vet calls hit hold-then-voicemail during busy clinic hours",
    voiceGreeting: "Thanks for calling {co} — is your pet having an emergency, or are you booking a visit?",
    voiceTryLines: ["“My dog's been vomiting.”", "“Need to book a vaccine.”", "“Can I refill my cat's meds?”"],
    chat: [
      { from: "customer", text: "My dog ate something and keeps throwing up" },
      { from: "agent", text: "Let's check — how many times in the last few hours, and is he still alert and drinking water?" },
      { from: "customer", text: "Three times, still alert" },
      { from: "agent", text: "I'd like a vet to see him today. We have 2:30pm open — can you make that, or should I flag it as urgent now?" },
    ],
    priceLine: "Live on your phone line in 14 days · from $1,997/mo",
  },
  {
    id: "insurance",
    niche: "Insurance Agency",
    emoji: "🛡️",
    accent: "#1D4ED8",
    defaultCompany: "Gulfshore Insurance",
    city: "Tampa",
    heroLead: "Every quote request worked",
    heroItalic: "before the lead price-shops elsewhere.",
    subhead: "Your AI line captures quote details, qualifies the line of business, books the agent, and never lets a warm lead sit in voicemail.",
    chips: ["Quote intake", "Line-of-business routing", "Agent booking", "Renewal calls"],
    services: [
      { title: "Quote intake", body: "Auto, home, and life details captured and routed to the right producer." },
      { title: "Agent scheduling", body: "Callbacks and review calls booked into your agents' calendars." },
      { title: "Renewal + cross-sell", body: "Renewal reminders handled; bundle opportunities flagged." },
      { title: "After-hours capture", body: "Evening and weekend quote calls captured, not lost." },
    ],
    painStat: "50%",
    painLabel: "of insurance quote calls go to the first agent who picks up",
    voiceGreeting: "Thanks for calling {co} — are you looking for auto, home, life, or business coverage?",
    voiceTryLines: ["“I need a car insurance quote.”", "“Can you bundle home and auto?”", "“My renewal went up.”"],
    chat: [
      { from: "customer", text: "Looking for a cheaper auto quote" },
      { from: "agent", text: "Happy to help you compare. Are you insuring one vehicle or more, and do you currently have coverage?" },
      { from: "customer", text: "Two cars, currently with Geico" },
      { from: "agent", text: "We can usually beat that, especially bundled with home. Want a call with our agent Sam today at 4pm?" },
    ],
    priceLine: "Live on your phone line in 10 days · from $1,997/mo",
  },
  {
    id: "mortgage",
    niche: "Mortgage Broker",
    emoji: "🏦",
    accent: "#155E75",
    defaultCompany: "Keystone Mortgage",
    city: "Tampa",
    heroLead: "Every rate inquiry captured",
    heroItalic: "before the borrower calls another lender.",
    subhead: "Your AI line captures loan purpose, pre-qualifies basics, books the loan officer, and works leads the moment rates move.",
    chips: ["Loan intake", "Pre-qual screening", "LO booking", "Rate-drop callbacks"],
    services: [
      { title: "Loan intake", body: "Purchase vs. refi, price range, and timeline captured up front." },
      { title: "Pre-qual basics", body: "Credit-range and down-payment basics screened before the LO call." },
      { title: "Loan-officer booking", body: "Qualified borrowers booked straight into the right LO's calendar." },
      { title: "Rate-drop outreach", body: "Past leads re-engaged automatically when rates move in their favor." },
    ],
    painStat: "53%",
    painLabel: "of mortgage leads close with the first lender to respond",
    voiceGreeting: "Thanks for calling {co} — are you buying a home, or looking to refinance?",
    voiceTryLines: ["“What are your rates today?”", "“I want to get pre-approved.”", "“Can I lower my payment?”"],
    chat: [
      { from: "customer", text: "Thinking about refinancing, what are rates?" },
      { from: "agent", text: "Rates move daily — to quote you accurately, roughly what's your current rate and loan balance?" },
      { from: "customer", text: "6.9%, about $320k" },
      { from: "agent", text: "There may be real savings there. Want a 15-min call with our loan officer Priya today at 3pm to run the numbers?" },
    ],
    priceLine: "Live on your phone line in 14 days · from $1,997/mo",
  },
  {
    id: "accounting",
    niche: "Accounting / CPA",
    emoji: "📊",
    accent: "#4338CA",
    defaultCompany: "Ledger & Co. CPAs",
    city: "Tampa",
    heroLead: "Every tax-season call booked",
    heroItalic: "while your team's heads-down on returns.",
    subhead: "Your AI line screens new clients, books consults, triages bookkeeping vs. tax, and answers status questions 24/7.",
    chips: ["New-client intake", "Consult booking", "Service triage", "Tax-season surge"],
    services: [
      { title: "New-client intake", body: "Individual vs. business, entity type, and need captured to a structured form." },
      { title: "Consult scheduling", body: "Qualified prospects booked into the right CPA's calendar." },
      { title: "Service triage", body: "Bookkeeping, tax prep, and advisory routed to the right team." },
      { title: "Tax-season surge", body: "When January–April volume spikes, every call is still answered." },
    ],
    painStat: "40%",
    painLabel: "of tax-season inquiry calls never get a callback in time",
    voiceGreeting: "Thanks for calling {co} — are you calling about personal taxes, business accounting, or something else?",
    voiceTryLines: ["“I need my taxes done.”", "“Do you do bookkeeping for an LLC?”", "“Are you taking new clients?”"],
    chat: [
      { from: "customer", text: "Need help with my small business taxes" },
      { from: "agent", text: "Happy to help. Is your business an LLC, S-corp, or sole prop, and do you have bookkeeping in place?" },
      { from: "customer", text: "LLC, books are a mess honestly" },
      { from: "agent", text: "We can clean that up and handle the return. Want a consult with one of our CPAs Thursday 10am or Friday 1pm?" },
    ],
    priceLine: "Live on your phone line in 14 days · from $1,997/mo",
  },
  {
    id: "catering",
    niche: "Catering",
    emoji: "🍴",
    accent: "#B91C1C",
    defaultCompany: "Tableside Catering",
    city: "Tampa",
    heroLead: "Every event inquiry captured",
    heroItalic: "before the planner books another caterer.",
    subhead: "Your AI line captures event details, quotes by headcount, books tastings, and routes corporate and wedding leads instantly.",
    chips: ["Event intake", "Headcount quoting", "Tasting booking", "Corporate + weddings"],
    services: [
      { title: "Event intake", body: "Date, headcount, venue, and budget captured to a structured lead." },
      { title: "Quote-on-call", body: "Per-head pricing estimated instantly with menu tier options." },
      { title: "Tasting booking", body: "Tastings scheduled and confirmed before the lead shops elsewhere." },
      { title: "Corporate accounts", body: "Recurring office catering and event clients set up automatically." },
    ],
    painStat: "1 in 3",
    painLabel: "catering inquiries book whoever answers and quotes first",
    voiceGreeting: "Thanks for calling {co} — what kind of event are you planning, and roughly how many guests?",
    voiceTryLines: ["“Wedding for 120 in June.”", "“Office lunch for 30 Friday.”", "“Do you do tastings?”"],
    chat: [
      { from: "customer", text: "Planning a wedding for about 120 people" },
      { from: "agent", text: "Congratulations! Do you have a date and venue, and are you thinking plated, buffet, or stations?" },
      { from: "customer", text: "June 14th, buffet style" },
      { from: "agent", text: "Buffet for 120 runs roughly $55–$75/head. Want to book a tasting? I have next Tuesday 6pm open." },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "barbershop",
    niche: "Barbershop",
    emoji: "💈",
    accent: "#374151",
    defaultCompany: "Kingsman Barber Co.",
    city: "Tampa",
    heroLead: "Every chair booked",
    heroItalic: "without your barbers stopping mid-cut.",
    subhead: "Your AI line books cuts and fades to the right barber, fills no-shows from the waitlist, and handles walk-in wait-time questions.",
    chips: ["Appointment booking", "Barber matching", "Waitlist fills", "Membership"],
    services: [
      { title: "Appointment booking", body: "Cuts, fades, and beard work booked to the requested barber." },
      { title: "Walk-in management", body: "Wait-time questions answered; walk-ins added to the queue." },
      { title: "Waitlist fills", body: "Cancellations instantly offered to clients waiting for a slot." },
      { title: "Membership + packages", body: "Monthly cut memberships sold and renewed on the call." },
    ],
    painStat: "1 in 4",
    painLabel: "booking calls come in while every chair is full",
    voiceGreeting: "Thanks for calling {co} — booking a cut, and do you have a barber you usually see?",
    voiceTryLines: ["“Cut and beard trim with Marcus.”", "“Any walk-in time today?”", "“How much for a fade?”"],
    chat: [
      { from: "customer", text: "Can I get in with Marcus today?" },
      { from: "agent", text: "Let me check Marcus's chair — he has 4:30 or 6pm open. Cut, or cut and beard?" },
      { from: "customer", text: "Cut and beard" },
      { from: "agent", text: "That's $45, about 45 minutes. Want 4:30? I'll text you a confirmation and reminder." },
    ],
    priceLine: "Live on your phone line in 7 days · from $1,997/mo",
  },
  {
    id: "physical-therapy",
    niche: "Physical Therapy",
    emoji: "🩺",
    accent: "#0891B2",
    defaultCompany: "Motion First PT",
    city: "Tampa",
    heroLead: "Every new-patient referral booked",
    heroItalic: "before it slips to another clinic.",
    subhead: "Your AI line screens referrals and insurance, books evals, and fills cancellations so your schedule stays full.",
    chips: ["Referral intake", "Insurance screening", "Eval booking", "Cancellation fills"],
    services: [
      { title: "Referral intake", body: "Referring provider, body region, and insurance captured up front." },
      { title: "Evaluation booking", body: "Initial evals scheduled to the right therapist with notes attached." },
      { title: "Insurance + authorization", body: "Coverage and visit limits screened on the call." },
      { title: "Cancellation fills", body: "Open slots offered to your waitlist to keep utilization high." },
    ],
    painStat: "36%",
    painLabel: "of PT referrals never convert because the call goes unanswered",
    voiceGreeting: "Thanks for calling {co} — do you have a referral from your doctor, and what area are we treating?",
    voiceTryLines: ["“My doctor referred me for my knee.”", "“Do you take Medicare?”", "“How soon can I start?”"],
    chat: [
      { from: "customer", text: "Got a referral for my shoulder, want to start PT" },
      { from: "agent", text: "Great — do you have the referral handy, and what insurance are you using?" },
      { from: "customer", text: "Yes, and I have Aetna" },
      { from: "agent", text: "We're in-network with Aetna. I can book your evaluation Monday 9am or Tuesday 2pm — which works?" },
    ],
    priceLine: "Live on your phone line in 14 days · from $1,997/mo",
  },
];

export function getNicheSite(id: string | undefined): NicheSite | undefined {
  if (!id) return undefined;
  const n = NICHE_SITES.find((x) => x.id === id.toLowerCase());
  // Treat `disabled` niches as not-found for the public template route.
  if (!n || n.disabled) return undefined;
  return n;
}

/** Active (non-disabled) niches — for galleries, search, bulk export. */
export const ACTIVE_NICHE_SITES: NicheSite[] = NICHE_SITES.filter((n) => !n.disabled);
