// src/pages/portal/Documents.tsx
// v76-a: Catalog of customer-facing documents. Links are placeholders that
// resolve once the customer's contract and exports are generated.

import { useOutletContext } from "react-router-dom";
import type { Customer } from "@/lib/portal";
import { FileText, Download, Lock } from "lucide-react";

const NAVY = "#042C53";

type Ctx = { customer: Customer | null; email: string };

type Doc = { key: string; label: string; description: string; available: boolean; href?: string };

export default function PortalDocuments() {
  const { customer } = useOutletContext<Ctx>();
  const isLive = customer?.agent_status === "production";

  const docs: Doc[] = [
    { key: "contract", label: "Service contract", description: "Your signed MSA + statement of work.", available: !!customer, href: customer ? "mailto:alexander@trainyouragent.com?subject=Contract%20copy%20request" : undefined },
    { key: "dpa", label: "Data Processing Agreement", description: "GDPR/CCPA addendum. Required for most enterprise vendors.", available: true, href: "/legal/dpa" },
    { key: "invoices", label: "Invoices (PDF)", description: "Full billing history exports. Generated by Stripe.", available: false },
    { key: "training-data", label: "Agent training data export", description: "Your knowledge base + fine-tune corpus, downloadable as JSON/CSV.", available: isLive },
    { key: "transcripts", label: "Conversation transcripts export", description: "Full 90-day call log, JSON. For compliance and analytics.", available: isLive },
  ];

  return (
    <div className="glass-panel p-6 sm:p-8 holo-cyan">
      <div className="mb-8">
        <h1 className="text-[26px] leading-tight tracking-tight flex items-center gap-2 title-mono" style={{ fontFamily: "Inter Tight, system-ui, sans-serif" }}>
          <span className="trinity-orb" aria-hidden="true" />
          Documents <span className="text-[10px] align-super opacity-60">(KB / Exports)</span>
        </h1>
        <p className="mt-2 text-[14px]" style={{ color: "rgba(4,44,83,0.65)" }}>
          Everything you need for compliance, audits, and migration. Available to you in writing.
        </p>
        <div className="brand-note mt-1">100% REAL • AUDIT-READY • NO SYNTHETIC RECORDS</div>
      </div>

      <ul className="space-y-2">
        {docs.map((d) => (
          <li
            key={d.key}
            className="glass-panel p-4 flex items-center gap-4"
            style={{ borderColor: "rgba(4,44,83,0.1)" }}
          >
            <div className="w-10 h-10 rounded-md flex items-center justify-center flex-shrink-0" style={{ background: "rgba(4,44,83,0.06)", color: NAVY }}>
              <FileText size={16} strokeWidth={1.6} />
            </div>
            <div className="flex-1 min-w-0">
              <div className="text-[14px] font-medium" style={{ fontFamily: "Inter Tight, system-ui, sans-serif" }}>{d.label}</div>
              <div className="text-[12.5px]" style={{ color: "rgba(4,44,83,0.6)" }}>{d.description}</div>
            </div>
            {d.available && d.href ? (
              <a
                href={d.href}
                className="btn-glass text-[12px] px-3 py-1.5"
                style={{ color: NAVY }}
              >
                <Download size={13} /> Download
              </a>
            ) : (
              <span className="inline-flex items-center gap-1.5 text-[12px] px-3 py-1.5 glass-panel" style={{ color: "rgba(4,44,83,0.5)" }}>
                <Lock size={12} /> {d.available ? "Request" : "After launch"}
              </span>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}
